# Generated by Django 4.2.4 on 2023-09-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy_rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
